# Generated by Django 5.1 on 2024-08-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_class_assingment_alter_class_lesson'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bootcamps',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_bootcamps', to='learning.bootcamp'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_classes', to='learning.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bootcamps',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_bootcamps', to='learning.bootcamp'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_classes', to='learning.class'),
        ),
    ]
