# Generated by Django 5.1 on 2024-08-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_class_assingment_alter_class_lesson'),
        ('user', '0002_alter_student_bootcamps_alter_student_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='bootcamps',
            field=models.ManyToManyField(blank=True, related_name='student_bootcamps', to='learning.bootcamp'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='student_classes', to='learning.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bootcamps',
            field=models.ManyToManyField(blank=True, related_name='teacher_bootcamps', to='learning.bootcamp'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teacher_classes', to='learning.class'),
        ),
    ]
