# Generated by Django 5.1 on 2024-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_password_teacher_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123456', max_length=255),
        ),
    ]
